* На любой странице левое меню содержит подменю - как это подменю открывается
При наведении мыши, при клике, при попадании в раздел (с перезагрузкой
страницы). Чтобы определить как это нужно делать нужна карта сайта.
* Где в сетке находится логотип - в шапке или левом меню.
И, соответственно, если он находится в левом столбце, то
горизонтальное меню мы можем поместить в правый столбец, чтобы оно
тянулось. Если оно тянуться не будет - то зачем мы боремся за
резиновый дизайн?
* Нужна ли нам графика в горизонтальном меню?
Если мы хотим сделать в горизонтальном меню графические элементы,
вроде закругленных уголков, или выделения текущего активного меню
графикой, которая похожа на вкладки, то нам потребуется чтобы все
элементы горизонтального меню имели одинаковый размер. Но уже сейчас у
нас есть короткий пункт "акции" и длинный "личный кабинет",
соответственно в дизайне это будет смотреться разрывами между пунктами
меню. Если мы откажемся от закругленных уголков - в пользу заливки
цветом фона, то меню в целом будет выглядеть опрятнее.
* Кнопки "добавить в избранное" "сделать стартовой" и "rss"
А также не присутствующие "карта сайта" и "написать нам". Они
практически никогда не используются, но занимают самое лучшее место,
мешая остальным элементам. Лучше сократить их до размера пиктограмм,
как это сделано на большинстве современных сайтов.
* Поиск
Поиск - важная функциональная часть сайта и лучше расположить его
поближе к логотипу, а не под левым меню, которое может разрастись
настолько, что чтобы воспользоваться поиском придется проматывать
страницу вниз.
* Так ли нам нужны горизонтальное меню?
Ведь мы рискуем, что при добавлении пунктов в него или просто
просмотре на устройстве с низким разрешением (планшет, телефон) оно
разрушит нам весь дизайн. Может быть лучше заменить его на
вертикальные меню подразделов?
* Использование вкладок
В отличие от настольных программ в вебе практически не используется
метафора вкладок, из-за чего интерфейс выглядит непонятным. Мы можем
реализовать те же функции с использованием вертикальных меню
подразделов.

